Repository Hashir311/SplitIT, pull requests merged in 2024-10, with the labels that each got.

#3 fixes #2
  SplitIT/templates/group.html
Labels: hacktoberfest, hacktoberfest-accepted

#4 Fix : Resolve flickering issue in delete modal #1
  SplitIT/templates/group_list.html
Labels: hacktoberfest, hacktoberfest-accepted

#9 Fixes #8: Create LICENSE
  LICENSE
Labels: documentation, hacktoberfest

#24 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#25 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#31 Fixed font color in profile page
  SplitIT/templates/profile.html
Labels: enhancement, hacktoberfest

#34 remove quote block
  SplitIT/templates/dashboard_base.html
Labels: enhancement, hacktoberfest
